name: foodgram

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: shibaevvv/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/app/docs
  frontend:
    image: shibaevvv/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: shibaevvv/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "8800:80"
    volumes:
      - static:/staticfiles
      - media:/media
      - docs:/docs