server {
  listen 80;
  server_tokens off;
  client_max_body_size 10M;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/api/;
    client_max_body_size 20M;
  }

  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
    client_max_body_size 20M;
  }

  location /api/docs/ {
    alias /docs/;
    index redoc.html
    try_files $uri /redoc.html;
  }

  location /s/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/s/;
  }

  location /media/ {
    alias /media/;
  }

  location / {
    alias /staticfiles/;
    index  index.html index.htm;
    try_files $uri /index.html;
  }
}